import { Inter } from "next/font/google";
import { draftMode } from "next/headers";

import { sansfont } from "@/app/fonts";
import VisualEditing from "@/app/components/VisualEditing";

import "./globals.css";

import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${sansfont.variable}`}>
      <head>
        <link rel="icon" href="/docs/icon-32x32.png" sizes="32x32" />
        <link rel="icon" href="/docs/icon-192x192.png" sizes="192x192" />
        <link rel="apple-touch-icon" href="/docs/icon-180x180.png" />
        <meta name="msapplication-TileImage" content="/docs/icon-270x270.png" />
      </head>
      <body className={inter.className}>
        {children}
        {draftMode().isEnabled && <VisualEditing />}
      </body>
    </html>
  );
}
